# Generated by Django 6.0.5 on 2026-05-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "платеж", "verbose_name_plural": "платежи"},
        ),
    ]
