# Generated by Django 6.0.6 on 2026-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=850, null=True, verbose_name="Ссылка_на_оплату"),
        ),
    ]
