# Generated by Django 6.0.6 on 2026-06-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name="Статус_оплаты"),
        ),
    ]
