# Generated by Django 6.0.6 on 2026-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default="2026-06-14 23:59:15.976943+03", verbose_name="Последняя_авторизация"
            ),
            preserve_default=False,
        ),
    ]
