# Generated by Django 6.0.5 on 2026-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/courses/", verbose_name="Превью"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/lessons/", verbose_name="Превью"),
        ),
    ]
