# Generated by Django 6.0.5 on 2026-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0002_alter_course_image_alter_lesson_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка_на_видео"),
        ),
    ]
