# Generated by Django 6.0.6 on 2026-06-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0006_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Последнее_обновление"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Последнее_обновление"),
        ),
    ]
